### ISSUE TITLE
ESM-Related Compilation Error After Installing Specific NestJS Packages

### ISSUE THREAD

**Issue by eagle-head** [nest-modules/mailer#1071]
**Describe the bug**
After installing specific packages for my NestJS project, I am unable to run the `yarn start:dev` command without encountering an ESM-related error.

**To Reproduce**
1. Install the following libraries:
    - "@nestjs-modules/mailer": "^1.9.1"
    - "handlebars": "^4.7.8"
    - "nodemailer": "^6.9.6"
    - "@types/nodemailer": "^6.4.13"
2. Run the command 'yarn start:dev'.
3. Observe the ESM-related error.

**Expected behavior**
I expected the `yarn start:dev` command to execute without issues.

**Error Log**
```
yarn start:dev
yarn run v1.22.19
$ nest start --watch
/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/wrap-ansi/index.js:2
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/string-width/index.js from /Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/wrap-ansi/index.js not supported.
Instead change the require of /Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/string-width/index.js in /Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/wrap-ansi/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/wrap-ansi/index.js:2:21)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/utils/screen-manager.js:4:18)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/prompts/base.js:14:23)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/prompts/list.js:11:14)
    at promptModule.restoreDefaultPrompts (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/inquirer.js:61:33)
    at inquirer.createPromptModule (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/inquirer.js:72:16)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/inquirer/lib/inquirer.js:84:28)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/lib/utils/project-utils.js:4:18)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/actions/generate.action.js:9:25)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/actions/index.js:19:14)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/commands/command.loader.js:5:19)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/commands/index.js:17:14)
    at Object.<anonymous> (/Users/eduardokohn/Documents/personal.nosync/prisma/drink-water-api/node_modules/@nestjs/cli/bin/nest.js:5:20) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Package.json:**
```json
{
  "name": "drink-water-api",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs-modules/mailer": "^1.9.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.0.0",
    "@nestjs/jwt": "^10.1.1",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^10.0.2",
    "@nestjs/platform-express": "^10.0.0",
    "@nestjs/throttler": "^5.0.0",
    "@prisma/client": "^5.4.2",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "handlebars": "^4.7.8",
    "nodemailer": "^6.9.6",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/nodemailer": "^6.4.13",
    "@types/supertest": "^2.0.12",
    "@types/uuid": "^9.0.5",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "prisma": "^5.4.2",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

**Desktop:**
 - OS: MacOS Ventura 13.5.2
 - Hardware: MacBook Pro with Apple M1 Pro chip and 16 GB memory
 - Version: (based on the provided packages) `yarn@1.22.19`, `node 18.17.1`, and `npm 9.6.7`

**Additional context**
The project no longer compiles after the installation of the mentioned libraries.

**Comment by eagle-head** [comment]
It works using `npm` instead `yarn`.

**Comment by micalevisk** [comment]
I faced this in the past due to some error in my lock file

have you tried to clean up your project?

```bash
rm -rf node_modules package-lock.json
```

**Comment by JSouza27** [comment]
I also had this problem and noticed that it happens after installing the `@types/nodemailer` package with `yarn`. I solved it using `npm`.

**Comment by SeyedMostafaHosseinian** [comment]
> I faced this in the past due to some error in my lock file
> 
> have you tried to clean up your project?
> 
> ```shell
> rm -rf node_modules package-lock.json yarn.lock
> ```
> 
> Also, not sure if you have `@nestjs/cli` globally installed but I'd suggest you to uninstall it - use the local one instead (`yarn nest`/`npx nest`)

i had same problem and with your approach is fixed 👍
