### ISSUE TITLE
Unexpected token export (mailerconfig.ts)

### ISSUE THREAD

**Issue by kevinnascimento** [nest-modules/mailer#11]
Hi guys, 

When I run my project in production environment I have this issue:

```
 node dist/server/src/main.js

C:\Users\kevin\Documents\GitHub\backhoe\server\mailerconfig.ts:1
(function (exports, require, module, __filename, __dirname) { export = {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

Is there another way to declare the config using a file?

Thanks!

**Comment by cleitonper** [comment]
Hi,

if someone has the same issue and is using the [nestjs-community/nestjs-config](https://github.com/nestjs-community/nestjs-config) module, in order to solve this problem is necessary to exclude definition(`.d`) files in the `ConfigModule.load()` method.

To do this, change your `AppModule` to the following:

```javascript
@Module({
  imports: [
    ConfigModule.load(
      resolve(__dirname, 'config/**/!(*.d).{ts,js}'),
    ),
    // ... others modules here
  ],
  controllers: [ AppController ],
  providers: [ AppService ],
})
export class AppModule {}
```
