### ISSUE TITLE
Forced to install `pug` and `handlebars`

### ISSUE THREAD

**Issue by leosuncin** [nest-modules/mailer#125]
Due that `HandlebarsAdapter` and `PugAdapter` are exported from `dist/index.js`

<details>
<summary>Stacktrace</summary>
<pre>
Error: Cannot find module 'handlebars'
Require stack:
- /home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
- /home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/index.js
- /home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/index.js
- /home/user/projects/chatcord/dist/app.module.js
- /home/user/projects/chatcord/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._resolveFilename (/home/user/projects/chatcord/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/index.js:7:28)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js',
    '/home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/dist/index.js',
    '/home/user/projects/chatcord/node_modules/@nestjs-modules/mailer/index.js',
    '/home/user/projects/chatcord/dist/app.module.js',
    '/home/user/projects/chatcord/dist/main.js'
  ]
}
</pre>
</details>

**Comment by juandav** [comment]
```
yarn add handlebars
```

**Comment by juandav** [comment]
pug and handlebars is optional dependencies

**Comment by juandav** [comment]
check Readme

**Comment by leosuncin** [comment]
I don't want to use a template engine just plain text

**Comment by leosuncin** [comment]
Check out my repo

https://github.com/leosuncin/nest-modules-mailer-issue-125

It won't start without pug and handlebars installed, there aren't optional

**Comment by leosuncin** [comment]
Either way you need both templates installed to run

With only pug engine https://github.com/leosuncin/nest-modules-mailer-issue-125/tree/with-pug-templates

With only handlebars engine https://github.com/leosuncin/nest-modules-mailer-issue-125/tree/with-handlebars-templates

**Comment by dimalakh** [comment]
I have the same issue, the system pushes me to install both (pug and handlebars at the same time), if I remove one of them (for example handlebars because I don't use it) app crashes

**Comment by gperdomor** [comment]
Same here...

**Comment by juandav** [comment]
Ok thanks for reporting the bug, this should work in v1.3.22

**Comment by fluky** [comment]
@juandav, just took a glance at your changes for this.  I don't think that is going to fix it, you moved them from peerDependencies to optionalDependencies but the problem is not an error when running yarn/npm, the error is a compile time error when running or building the nest server.

**Comment by leosuncin** [comment]
@juandav now `pug` and `handlebars` are hoisted from `@nestjs-modules/mailer` and only works if don't prune `devDependencies`
