### ISSUE TITLE
Issue on prod

### ISSUE THREAD

**Issue by Araknos** [nest-modules/mailer#127]
MailerModule is working fine on dev but not on prod:

Module:

```
imports: [
        // NodeMailer
        MailerModule.forRoot({
            transport: `smtps://mg.com@gmail.com:${password}@smtp.gmail.com`,
            defaults: {
                from: '"No Reply" <mg.com@gmail.com>',
            },
            template: {
                dir: __dirname + '/templates',
                adapter: new HandlebarsAdapter(), // or new PugAdapter()
                options: {
                    strict: true,
                },
            },
        }),
    ],
```
Service:

```
sendEmail(recipient: string, subject: string, text: string, html: string = text): Promise<any> {
        return this.mailerService.sendMail({
            to: recipient,
            from: 'mg.com@gmail.com',
            subject: subject,
            text: text,
            html: html,
        });
    }
```

Logs from my server:

```
534-5.7.14 Please log in via your web browser and then try again.
Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 u7sm462421wmg.41 - gsmtp
at SMTPConnection._formatError (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
SMTPConnection._actionAUTHComplete (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
SMTPConnection._responseActions.push.str (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:550:26)
SMTPConnection._processResponse (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
at SMTPConnection._onData (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
at TLSSocket.SMTPConnection._onSocketData.chunk (/home/ew/mg/node_modules/nodemailer/lib/smtp-connection/index.js:195:44
at emitOne (events.js:116:13)
at TLSSocket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at TLSSocket.Readable.push (_stream_readable.js:208:10)
at TLSWrap.onread (net.js:607:20)
```
Any idea ?

**Comment by juandav** [comment]
1. Check that your email and password is correct for the gmail smtp.
2. Verify from gmail that this mail is enabled for transport. Permissions or other.
