### ISSUE TITLE
I can't use my Handlebars template

### ISSUE THREAD

**Issue by taksumaki** [nest-modules/mailer#175]
Previously I used the package "@ nest-modules / mailer" but now I went to "@ nestjs-modules / mailer" and it stopped working since now I get an error when using my Handlebar template, here the error when trying to send the email.
```console
(node:11308) UnhandledPromiseRejectionWarning: Error: Error: Unexpected } (line 75, char 9)
    at module.exports (C:\Users\Sawako\Documents\Kodachi\Apps\Backend\api-rest\node_modules\inline-css\lib\inline-css.js:65:15)     
    at C:\Users\Sawako\Documents\Kodachi\Apps\Backend\api-rest\node_modules\inline-css\lib\inlineContent.js:22:27
    at C:\Users\Sawako\Documents\Kodachi\Apps\Backend\api-rest\node_modules\extract-css\index.js:37:16
    at C:\Users\Sawako\Documents\Kodachi\Apps\Backend\api-rest\node_modules\batch\index.js:161:14
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:11308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on 
unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
My code
```ts
this._mailService
          .sendMail({
            to: userAccount.email.key,
            from: 'test@gmail.com',
            subject: 'Activation account | Kodachi - The best anime tracker',
            template: 'verify_email_request',
            context: {
              name: 'cf1a3f828287',
              token: 'cf1a3f828287',
              activate_account_url: 'Test',
              ip: 'Test',
            },
          })
```

I don't know what to do to fix it, please help me.

**Comment by taksumaki** [comment]
I realized that it was an error in my template, so I had to redo it since I was not in trouble and the problem was solved.
