### ISSUE TITLE
sendMail throw exception -  Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by afidosstar** [nest-modules/mailer#563]
### Error

```log
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.setHeader (node:_http_outgoing:579:11)
    at ServerResponse.header (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/express/lib/response.js:264:10)
    at ExpressAdapter.reply (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/@nestjs/platform-express/adapters/express-adapter.js:24:57)
    at ExceptionsHandler.handleUnknownError (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/@nestjs/core/exceptions/base-exception-filter.js:33:24)
    at ExceptionsHandler.catch (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)
    at ExceptionsHandler.next (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)
    at /Users/afidos/Dev/sfp/SFP/grh-api/node_modules/@nestjs/core/router/router-proxy.js:24:35
    at Layer.handle_error (/Users/afidos/Dev/sfp/SFP/grh-api/node_modules/express/lib/router/layer.js:71:5)
```  

   ### My code
   
```ts
export async function mailSender (mailer: MailerService, data: NotifyDataMAIL): Promise<NotificationEntity>{
    const notification = new NotificationEntity();

    try {
        notification.start_date  = new Date();
        notification.data = data;

        const options:ISendMailOptions = {
            ...omit(data,['isText','body']),
            [data.isText ? 'text' : 'html']: data.body};

        console.log('sendMail',options);

        const response = await mailer.sendMail(options);

        notification.end_date  = new Date();
        notification.response = response;
        notification.success =  true;

    }catch (e) {

        notification.end_date  = new Date();
        notification.response = Object(e);
        notification.success =  false;

    }
    return notification;
}
```
### controller 
```ts
@Post('test')
    @HttpCode(HttpStatus.NO_CONTENT)
    async resetPasswordRequest(@Body() body) {
         await mailSender(this.mailerService, body)
   };
```

**Comment by danielehrhardt** [comment]
Did you found a solution?
