### ISSUE TITLE
Cannot destructure property 'templateName' of 'precompile(...)'

### ISSUE THREAD

**Issue by hddananjaya** [nest-modules/mailer#570]
Hi all, 🦄

Config:
```
    "@nestjs-modules/mailer": "^1.6.0",
    "nodemailer": "^6.5.0",
    "handlebars": "^4.7.7",
```
I'm trying to use with handlebars.

App Module:
```javascript
@Module({
  imports: [
    UserModule,
    AdminModule,
    HotelModule,
    TypeOrmModule.forRoot(),
    ConfigModule.forRoot({ isGlobal: true }),
    MailerModule.forRootAsync({
      useFactory: () => ({
        transport:
          'smtps://no-reply@XXX:XXX@XXX.com',
        defaults: {
          from: '"XXX" <no-reply@XXX.com>',
        },
        template: {
          dir: path.resolve(__dirname, 'templates'),
          adapter: new HandlebarsAdapter(),
          options: {
            strict: true,
          },
        },
      }),
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
``` 
Service:

```javascript
import { Injectable } from '@nestjs/common';
import { MailerService } from '@nestjs-modules/mailer';

@Injectable()
export class UserMailService {
  constructor(private readonly mailerService: MailerService) {}

  sendEmailConfirmation(): void {
    this.mailerService
      .sendMail({
        to: 'test@nestjs.com',
        from: 'noreply@nestjs.com',
        subject: 'Testing Nest Mailermodule with template ✔',
        template: '/welcome',
      })
      .then((success) => {
        console.log(success);
      })
      .catch((err) => {
        console.log(err);
      });
  }
}
```
I get this error when I use templates.
```
TypeError: Cannot destructure property 'templateName' of 'precompile(...)' as it is undefined.
    at HandlebarsAdapter.compile (/mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js:52:17)
    at /mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:48:40
    at processPlugins (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:279:13)
    at /mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:283:17
    at Mail._convertDataImages (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:387:20)
    at Mail._defaultPlugins.compile (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:31:41)
    at processPlugins (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:279:13)
    at Mail._processPlugins (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:287:9)
    at Mail.sendMail (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:164:14)
    at MailerService.<anonymous> (/mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:74:51)
(node:8093) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/welcome.hbs'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at precompile (/mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js:34:41)
    at HandlebarsAdapter.compile (/mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js:52:34)
    at /mnt/c/Users/user/Desktop/web/api/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:48:40
    at processPlugins (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:279:13)
    at /mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:283:17
    at Mail._convertDataImages (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:387:20)
    at Mail._defaultPlugins.compile (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:31:41)
    at processPlugins (/mnt/c/Users/user/Desktop/web/api/node_modules/nodemailer/lib/mailer/index.js:279:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 I manually copied templates folder to `dist` to check whether the problem is with paths.
But it asks for `templateName` which I didn't provide.

Thanks!

**Comment by hddananjaya** [comment]
I was able to fix this by adding a `./` to template; as mentioned in #569 
Please close this issue if not needed. Thanks.

**Comment by Subalee** [comment]
That is actually not a complete solution, at least not for me.

What you actually have to do is update `nest-cli.json` to actually copy the templates to the `dist` folder

`nest-cli.json`
```json
"sourceRoot": "src",
"root": "./",
"compilerOptions": {
    "assets": [
      {
        "include": "notification/email-templates/**/*.hbs",
        "outDir": "dist/src"
      }
    ],
    "watchAssets": true
  }
  ```

where `notification` is the directory of my module and and my templates are inside the `email-templates` directory.
The path is actually copied that's why the `outDir` only has `dist/src` there.

however you still need to include the `./[template-name]` when trying to send an email.

I actually figured this out thanks to this [discussion](https://github.com/notiz-dev/notiz/discussions/167)

**Comment by emilenfc** [comment]
Thank you @subalee

**Comment by joler023** [comment]
thank you @subalee

**Comment by RashJrEdmund** [comment]
thank you @subalee

**Comment by RashJrEdmund** [comment]
thank you @subalee 

- Input
![Screenshot from 2024-07-06 08-25-18](https://github.com/nest-modules/mailer/assets/116172031/ae4f239b-b73f-4967-8350-b760f251a90d)

- OUtput in dist
![Screenshot from 2024-07-06 08-28-37](https://github.com/nest-modules/mailer/assets/116172031/77da68b2-b919-4993-9b96-0cd74f24e56f)

**Comment by RashJrEdmund** [comment]
thank you @subalee 

- Input
![Screenshot from 2024-07-06 08-32-15](https://github.com/nest-modules/mailer/assets/116172031/d4004fe9-426a-4ad2-8a33-74f8e40e373b)


- OUtput in dist
![Screenshot from 2024-07-06 08-38-00](https://github.com/nest-modules/mailer/assets/116172031/cff915d7-3a38-4e92-988e-dee3bebb95be)

**Comment by IT-WIBRC** [comment]
@RashJrEdmund I encountered a problem with your config. It takes only the file with the template and files with the `.hbs` extension, and not the `images` folder and other one.

Here is my config:
`include: mail/templates/**`
`outDir: dist/src`

**Comment by shaimaHamila** [comment]
Hey, I faced a similar issue where Handlebars templates weren't being copied to the dist directory, causing errors when sending emails. Here's the solution that worked for me:

In the nest-cli.json file, I updated the assets configuration to include the templates directory like this:

```

{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
      {
        "include": "./templates/*",
        "outDir": "dist/modules/mail",
        "watchAssets": true
      }
    ],
    "watchAssets": true
  }
}
```
In the tsconfig.json, I added the following to ensure that the template files are correctly included during the build:

```

{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  },
  "include": ["src/**/*.ts", "src/templates/**/*.hbs"] //I added this
}
```
After applying these changes, the templates were correctly copied to the dist directory, and the email functionality worked fine.
