### ISSUE TITLE
Error: Unexpected socket close at Timeout._onTimeout

### ISSUE THREAD

**Issue by sonipranjal** [nest-modules/mailer#760]
```
Error: Unexpected socket close
    at Timeout._onTimeout
    node_modules/nodemailer/lib/smtp-transport/index.js:189:31)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```
I am using AWS SES; it was working 4/5 days ago but suddenly, what happened 🤔

```
MailerModule.forRoot({
      transport: {
        host: process.env.EMAIL_SERVER_HOST,
        secure: false,
        port: +process.env.EMAIL_SERVER_PORT,
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD,
        },
      },
      defaults: {
        from: `${process.env.EMAIL_FROM}`,
      },
      template: {
        dir: join(__dirname, 'templates'),
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }),
```

**Comment by sonipranjal** [comment]
Try to change the internet connection. It will work.
